import test from 'node:test';import assert from 'node:assert/strict';
import {hashPassword,verifyPassword,sameSecret,checkOrigin,cookieToken} from '../server/auth.mjs';
import {meeting,record,task} from '../server/validation.mjs';
import {executeTool,runAgent} from '../server/agents.mjs';import {AGENTS} from '../shared/world.mjs';
test('Senhas scrypt com salt, comparação e convites não triviais',async()=>{const hash=await hashPassword('uma-senha-longa-para-teste');assert.notEqual(hash,await hashPassword('uma-senha-longa-para-teste'));assert.ok(await verifyPassword('uma-senha-longa-para-teste',hash));assert.equal(await verifyPassword('senha-errada',hash),false);assert.equal(sameSecret('curta','curta'),false);assert.ok(sameSecret('x'.repeat(32),'x'.repeat(32)));});
test('CSRF: origem exata e cookie HttpOnly extraído',()=>{process.env.APP_ORIGIN='https://coop.example.com';assert.throws(()=>checkOrigin({headers:{origin:'https://evil.example'}}));assert.throws(()=>checkOrigin({headers:{}}));assert.doesNotThrow(()=>checkOrigin({headers:{origin:'https://coop.example.com'}}));assert.equal(cookieToken({headers:{cookie:'other=a; gsa_session=token; x=y'}}),'token');});
test('Validação de tarefas, finanças em centavos e horários',()=>{assert.throws(()=>record({title:'x',sector:'finance',kind:'expense',amount_cents:1.2}));assert.throws(()=>task({title:'x',sector:'sales',assignee:'intruso'}));assert.throws(()=>meeting({title:'x',starts_at:'invalid',ends_at:'invalid'}));assert.throws(()=>meeting({title:'x',starts_at:new Date().toISOString(),ends_at:new Date(Date.now()+5*3600000).toISOString()}));assert.equal(record({title:'Peças',sector:'supply',kind:'material',amount_cents:99}).amount_cents,null);});
test('Agentes: ferramentas reais respeitam setor e escrita exige confirmação',async()=>{const records=[];const drafts=[];const repo={records:async sector=>{records.push(sector);return[{title:'Registro real'}];},costs:async()=>[{kind:'expense',total_cents:'170000'}]};const sales=AGENTS.find(a=>a.id==='sales-lead'),finance=AGENTS.find(a=>a.id==='finance');await executeTool('list_records',{},sales,repo,drafts);assert.deepEqual(records,['sales']);assert.ok((await executeTool('analyze_costs',{},sales,repo,drafts)).error);assert.equal((await executeTool('analyze_costs',{},finance,repo,drafts)).totals[0].total_cents,'170000');const result=await executeTool('propose_task',{title:'Ligar para lead',sector:'sales',assignee:'vitor'},sales,repo,drafts);assert.equal(result.status,'awaiting_user_confirmation');assert.equal(drafts.length,1);assert.ok((await executeTool('propose_task',{title:'x',sector:'finance',assignee:'vitor'},sales,repo,drafts)).error);assert.ok((await executeTool('run_sql',{},sales,repo,drafts)).error);});
test('Sem chave de IA não fabrica respostas',async()=>{const prior=process.env.AI_API_KEY;delete process.env.AI_API_KEY;await assert.rejects(runAgent({}, {id:'vitor'},'eva','Oi'),e=>e.status===503);if(prior)process.env.AI_API_KEY=prior;});
